Add prune command

diff --git a/ethd b/ethd
--- a/ethd
+++ b/ethd
@@ -529,6 +529,93 @@ terminate() {
     echo
 }
 
+prune() {
+  __non_interactive=0
+  while :
+  do
+    if [ -z ${1+x} ]; then
+      break
+    fi
+    case "$1" in
+      --non-interactive)
+        __non_interactive=1
+        shift
+        ;;
+      *)
+        echo "Error: Unknown option: $1" >&2
+        exit 1
+        ;;
+    esac
+  done
+
+  if [ ! -f "./${ENV_FILE}" ]; then
+    echo "${ENV_FILE} configuration file not found, aborting."
+    exit 1
+  fi
+
+  if ! grep -q '^COMPOSE_FILE=.*avalanche\.yml' "${ENV_FILE}" 2>/dev/null ; then
+    echo "You do not appear to be using Avalanche, aborting."
+    exit 1
+  fi
+
+  if [ "$(df -P /var/lib/docker | awk '/[0-9]%/{print $(NF-2)}')" -lt 41943040 ]; then
+    echo "You do not have enough free disk space. Make sure this reads at least 40G free (Avail):"
+    df -h /var/lib/docker
+    echo ""
+    echo "Aborting."
+    exit 1
+  fi
+
+  rpc_line=$(grep '^HTTP_PORT=' "${ENV_FILE}")
+  regex='^HTTP_PORT=([0-9]+)'
+  if [[ ! "${rpc_line}" =~ ${regex} ]]; then
+    echo "Unable to determine HTTP_PORT, aborting."
+    exit 1
+  else
+    rpc_port="${BASH_REMATCH[1]}"
+  fi
+
+  set +e
+  sync_status=$(cmd run --rm --entrypoint wget ava-init -qO- "http://avalanche:$rpc_port/ext/bc/C/rpc" --header 'Content-Type: application/json' --post-data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}')
+  exitstatus=$?
+  if [ $exitstatus -ne 0 ]; then
+    echo "Avalanche RPC is not responding, aborting."
+    echo "wget response:"
+    cmd run --rm --entrypoint wget ava-init -O- "http://avalanche:$rpc_port/ext/bc/C/rpc" --header 'Content-Type: application/json' --post-data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}'
+    exit 1
+  fi
+  set -e
+
+  if [[ ! "${sync_status}" =~ "false" ]]; then
+    echo "Avalanche is not done syncing yet. Sync status:"
+    echo "${sync_status}"
+    echo ""
+    echo "Aborting."
+    exit 1
+  fi
+
+  if [ $__non_interactive = 0 ]; then
+    while true; do
+      read -rp "WARNING - this will stop Avalanche and prune its C-Chain database. Do you wish to continue? (No/Yes) " yn
+      case $yn in
+        [Yy]es ) break;;
+        * ) echo "Aborting, no changes made"; exit 1;;
+      esac
+    done
+  fi
+
+  echo
+  echo "Starting C-Chain prune"
+  echo
+  cmd run --rm set-prune-marker "touch /var/lib/ava/prune-marker"
+  cmd stop avalanche && cmd rm -f avalanche
+  start
+  echo
+  echo "Prune is running, you can observe it with './ethd logs -f avalanche'"
+  echo
+  echo "When prune is done, Avalanche will automatically start again."
+  echo
+}
 
 set_value_in_env() {
     # Assumes that "var" has been set to the name of the variable to be changed
@@ -607,6 +694,8 @@ help() {
     echo "     executes an arbitrary Docker Compose command. Use \"cmd help\" to list them"
     echo "  terminate"
     echo "     stops the ${__app_name} and destroys all data stores"
+    echo "  prune"
+    echo "     starts an offline prune of the C-chain"
     echo "  help"
     echo "      print this help screen"
     echo
@@ -690,7 +779,7 @@ if ! docompose --help >/dev/null 2>&1; then
 fi
 
 case "$__command" in
-    help|update|up|start|down|stop|restart|version|logs|cmd|terminate)
+    help|update|up|start|down|stop|restart|version|logs|cmd|terminate|prune)
         $__command "$@";;
     *)
         echo "Unrecognized command $__command"
